My
AsiAsiAsiA/ContactsList pull request #1
Opened 2018-11-23 11:53 UTC by AsiAsiAsiA

First Pull Request

2018-11-23 12:10 UTC, goblinr requested changes

2018-11-23 12:10 UTC, goblinr commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_7" project-jdk-name="1.8" project-jdk-type="JavaSDK">
Папку идеи - в gitignore нужно добавить

2018-11-23 12:10 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        setRetainInstance(true);
`setRetainInstance(true);` не стоит использовать для фрагментов у которых есть `View`

2018-11-23 12:10 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        contactArrayList = ContactsContentResolver.getContacts(getActivity());
Чтение контактов на главном потоке программы. Неприемлемо с точки зрения отзывчивого UI.
Так же не спрашивается разрешение на чтение контактов.

2018-11-23 12:10 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +                DetailFragment detailFragment = new DetailFragment();
Создание и инициализацию фрагмента принято делать в методе `newInstance` фрагмента.

2018-11-23 12:10 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/ContactsContentResolver.java
> +            cursor.close();
Закрывать курсор в `finally` блоке

2018-11-23 12:10 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/ContactsContentResolver.java
> +    private static ArrayList<Contact> contactArrayList;
Хранение списка контактов `static` контексте программы - не оправдано с точки зрения юзабилити приложения, т.к. для того что бы перезагрузить список контактов придется перезапускать приложение.

2018-11-23 12:10 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/ContactsContentResolver.java
> +            phoneCursor.close();
Закрывать курсор в `finally` блоке

2018-11-23 12:10 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        setRetainInstance(true);
`setRetainInstance(true);` не стоит использовать для фрагментов у которых есть `View`

2018-11-23 12:10 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        Contact contact = ContactsContentResolver.findContactById(contactId);
Чтение на главном потоке. Не спрашиваются разрешение на чтение.

2018-11-23 12:10 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +            itemView.setOnClickListener(new View.OnClickListener() {
`setOnClickListener` следует делать в конструкторе вьюхолдера.

2018-11-23 12:10 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/model/Contact.java
> +    private List<String> phoneNumbers;
`final` ко всем полям

2018-11-23 12:10 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/model/Contact.java
> +    }
`hashCode` и `equals`

2018-11-23 12:10 UTC, goblinr commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="8dp"
Имеет смысл дефолтные отступы выносить в ресурсы

2018-11-23 12:10 UTC, goblinr commented on app/src/main/res/layout/contacts_adapter_item.xml
> +        android:textSize="20dp"
размер текста в dp, необходимо использовать sp

2018-11-23 12:10 UTC, goblinr commented on app/src/main/res/layout/fragment_contact_list.xml
> +        android:textSize="20dp"
размер текста в dp, необходимо использовать sp 
размер дублируется, можно вынести в ресурсы

2018-11-23 12:12 UTC, RomanPozdeev requested changes

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        setRetainInstance(true);
По возможности стоит избегать retain фрагментов. В крайнем случае делать их без view, иначе утечки памяти

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +    public ContactListFragment() {
Можно, но не обязательно. Пустой конструктор есть у любого класса, если нет других конструкторов.

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +    private void sendDataToDetailFragment(String message, Fragment fragment) {
Эта логика должна быть внтури newInstance того фрагмента, который создается, как и создание фрагмента.

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        recyclerView.setAdapter(new ContactsAdapter(contactArrayList, new ContactsAdapter.OnItemClickListener() {
Лучше перейти на Java 8 и лямбды

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        contactArrayList = ContactsContentResolver.getContacts(getActivity());
Получение данных - лучше вынести в другой поток. getActivity - в данном случае лучше заменить на requireContext

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        recyclerView.setLayoutManager(new LinearLayoutManager(getContext()));
requireContext

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        FragmentTransaction fragmentTransaction = getFragmentManager().beginTransaction();
оформить как цепочку

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/ContactsContentResolver.java
> +    private static ArrayList<Contact> contactArrayList;
Во первых - List<Contact>, во вторых для чего нам он как статик?

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/ContactsContentResolver.java
> +        if (cursor != null) {
обернуть в try-finally

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/ContactsContentResolver.java
> +        ArrayList<String> listPhoneNumbers = new ArrayList<>();
List<>

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/ContactsContentResolver.java
> +            while (phoneCursor.moveToNext()) {
try-finally

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +public class DetailFragment extends Fragment {
Те же замечания что и по фрагменту выше

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        tvName.setText("Name: " + contact.getName());
Не должно быть захардкоженных строк

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/MainActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
Потерялась аннотация @Nullable

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +            itemView.setOnClickListener(new View.OnClickListener() {
listener-ы назначать в конструкторе viewholder'a

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +            name.setText("id: " + contact.getId() + " name: " + contact.getName());
Вынести в ресурсы

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/res/layout/activity_main.xml
> +<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Для чего тут ConstraintLayout?

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/res/layout/contacts_adapter_item.xml
> +        android:textSize="20dp"
в стили/размеры

2018-11-23 12:12 UTC, RomanPozdeev commented on app/src/main/res/layout/fragment_contact_list.xml
> +        android:textSize="20dp"
в стили/размеры

2018-11-26 16:14 UTC, goblinr requested changes

2018-11-26 16:14 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +            contactArrayList = contactsAsyncTask.get();
Проблема с отзывчивостью UI осталась. `get()` - блокирует текущий поток, до тех пор, пока результат асинхронной задачи не будет доступен.

2018-11-26 16:14 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +            contact = detailAsyncTask.get();
Проблема с отзывчивостью UI осталась. `get()` - блокирует текущий поток, до тех пор, пока результат асинхронной задачи не будет доступен.

2018-11-26 16:14 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/service/ContactsAsyncTask.java
> +        delegate.processFinish();
Посмотри, пожалуйста, этот мой комментарий к коду Ксении https://github.com/murrcha/it-univer/pull/3#discussion_r236052116 там подробно описана в чем здесь проблема и как ее решить. В данном конкретном случае, тебе нужно `AsyncResponse` сделать слабой ссылкой.

2018-11-27 12:58 UTC, goblinr requested changes

2018-11-27 12:58 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        recyclerView.setAdapter(contactsAdapter);
Инициализацию адаптера и лэйаут мэнеджера следует сделать 1 раз в `onViewCreated`

2018-11-27 12:58 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +    private static boolean READ_CONTACTS_GRANTED = false;
Не стоит хранить состояние разрешение в `static` - это не правильно. Состояние разрешения следует спрашивать всякий раз, когда требуется совершить действие требующее это разрешение и никак иначе.

2018-11-27 12:58 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        DetailAsyncTask detailAsyncTask = new DetailAsyncTask(contactId, this);
Не спрашиваются разрешение на чтение контактов.

2018-11-27 12:58 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/service/ContactsAsyncTask.java
> +        delegate.get().loadList(contacts);
Нельзя так работать с `WeakReference`. Делай так:
```java
AsyncResponseContactListFragment  callback = delegate.get();
if (callback != null) {
  callback.loadList(contacts);
}
```

2018-11-27 12:58 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/service/DetailAsyncTask.java
> +        delegate.get().loadContactFromContentProvider(contact);
Нельзя так работать с `WeakReference`

2018-11-27 13:01 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        DetailAsyncTask detailAsyncTask = new DetailAsyncTask(contactId, this);
тут я подумал, что логика программы никогда не дойдет до DetailFragment без разрешений

2018-11-27 13:02 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        DetailAsyncTask detailAsyncTask = new DetailAsyncTask(contactId, this);
Ошибаешься

2018-11-27 13:02 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        DetailAsyncTask detailAsyncTask = new DetailAsyncTask(contactId, this);
Понял

2018-11-27 13:04 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        DetailAsyncTask detailAsyncTask = new DetailAsyncTask(contactId, this);
Пользователь может свернуть приложение на `DetailFragment`, пойти в настройки и отключить разрешение, затем вернуться в приложение, фрагмент восстановится и запросит контакт - но получит уже SequrityException

2018-11-27 13:07 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/service/ContactsAsyncTask.java
> +        delegate.get().loadList(contacts);
получается `WeakReference` перед использованием всегда необходимо проверять на `null`?

2018-11-27 13:11 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/service/ContactsAsyncTask.java
> +        delegate.get().loadList(contacts);
Да. Почитай про модель памяти в Java про типы ссылок и как работает GC.

2018-11-27 17:29 UTC, goblinr requested changes

2018-11-27 17:29 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/service/ContactsAsyncTask.java
> +            delegate.get().loadList(contacts);
Так работать с `WeakReference` нельзя. Необходимо результат метода `get()` присвоить жесткой ссылке на стэке, а уже потом проверять эту жесткую ссылку на `null`

2018-11-27 17:29 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/service/DetailAsyncTask.java
> +            delegate.get().loadContactFromContentProvider(contact);
Так работать с `WeakReference` нельзя. Необходимо результат метода `get()` присвоить жесткой ссылке на стэке, а уже потом проверять эту жесткую ссылку на `null`

2018-11-27 17:31 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/service/ContactsAsyncTask.java
> +            delegate.get().loadList(contacts);
сейчас исправлю

2018-11-27 17:38 UTC, goblinr approved these changes

2018-11-27 17:38 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/service/DetailAsyncTask.java
> +        if (callback!=null){
пробелы

2018-11-28 06:44 UTC, RomanPozdeev requested changes

2018-11-28 06:44 UTC, RomanPozdeev commented on app/build.gradle
> +    implementation fileTree(include: ['*.jar'], dir: 'libs')
зависимости нужно указывать явно, в твоем случае этой строчки вообще быть не должно

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        args.putString("_id", id);
ключ - в константы

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        contactId = bundle.getString("_id", "Empty");
константы

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        tvName.setText(String.format("%s %s", getString(R.string.id), contact.getName()));
лично я бы избавился от String.format тут - есть перегруженный метод getString который может выполнить ту же работу

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +    public ContactsAdapter(Context context, List<Contact> contacts) {
конструктор должен быть расположен выше

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +    private final Context context;
поля между методами не стоит располагать

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +    private final Context context;
Ну и если подумать то контекст ты всегда можешь достать из вьюшек

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +    class ContactsViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
почему именно такая область видимости у VH?

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +            name.setText(String.format("%s %s %s %s",
тут тоже лучше избавиться от String.format

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +            itemClickListener.onClick(contacts.get(position).getId());
нет проверки на NO_POSTITION

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/service/AsyncResponseContactListFragment.java
> +public interface AsyncResponseContactListFragment {
Название интерфейса вводит в заблуждение - причем тут Fragment

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/service/AsyncResponseDetailFragment.java
> +public interface AsyncResponseDetailFragment {
тут то же замечание по названию

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/service/ContactsContentResolver.java
> +class ContactsContentResolver {
Ну это же не ContentResolver ), с тем же успехом можно было назвать ContactsActivity, ContactsApplication и т.д. Не стоит давать классам вводящие в заблуждения имена

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/service/ContactsAsyncTask.java
> +            callback.loadList(contacts);
На самом деле тоже не совсем хороший вариант - ссылка на объект еще может быть, но view уже будет уничтожен и при попытке установить значения - все крэшнется

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/res/layout/fragment_contact_list.xml
> +
лишняя пустая строка

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/res/layout/fragment_contact_list.xml
> +        android:scrollbars="vertical" />
а тут бы добавить

2018-11-28 06:44 UTC, RomanPozdeev commented on app/src/main/res/values/strings.xml
> +    <string name="detailFragment_title">Contact Detail</string>
в строках старайтесь группировать ресурсы по экранам (можно добавлять между строк комментарий)

2018-11-28 07:03 UTC, AsiAsiAsiA commented on app/src/main/res/layout/fragment_contact_list.xml
> +
убрал

2018-11-28 07:04 UTC, AsiAsiAsiA commented on app/src/main/res/layout/fragment_contact_list.xml
> +        android:scrollbars="vertical" />
добавил

2018-11-28 07:07 UTC, AsiAsiAsiA commented on app/src/main/res/values/strings.xml
> +    <string name="detailFragment_title">Contact Detail</string>
сгруппировал

2018-11-28 07:16 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +    private final Context context;
Таким образом?
`public ContactsViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.contacts_adapter_item, parent, false);
        Context context = parent.getContext();
        return new ContactsViewHolder(view);
}`

2018-11-28 07:17 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +    private final Context context;
Таким образом?
```
public ContactsViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        ...
        Context context = parent.getContext();
        ...
    }
```

2018-11-28 07:20 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/service/AsyncResponseContactListFragment.java
> +public interface AsyncResponseContactListFragment {
Ну я думал чтобы совпадало полностью с названием класса, в который придет ответ

2018-11-28 07:42 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +    public ContactsAdapter(Context context, List<Contact> contacts) {
исправил

2018-11-28 07:42 UTC, AsiAsiAsiA commented on app/build.gradle
> +    implementation fileTree(include: ['*.jar'], dir: 'libs')
удалил

2018-11-28 07:48 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +            name.setText("id: " + contact.getId() + " name: " + contact.getName());
вынес

2018-11-28 07:48 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +            itemView.setOnClickListener(new View.OnClickListener() {
исправил

2018-11-28 07:49 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        contactArrayList = ContactsContentResolver.getContacts(getActivity());
исправил

2018-11-28 07:57 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        setRetainInstance(true);
исправил

2018-11-28 07:57 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +    public ContactListFragment() {
исправил

2018-11-28 07:57 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +    private void sendDataToDetailFragment(String message, Fragment fragment) {
исправил

2018-11-28 07:58 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        recyclerView.setAdapter(new ContactsAdapter(contactArrayList, new ContactsAdapter.OnItemClickListener() {
исправил

2018-11-28 07:58 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        recyclerView.setLayoutManager(new LinearLayoutManager(getContext()));
исправил

2018-11-28 07:58 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        FragmentTransaction fragmentTransaction = getFragmentManager().beginTransaction();
исправил

2018-11-28 07:58 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/ContactsContentResolver.java
> +    private static ArrayList<Contact> contactArrayList;
исправил

2018-11-28 07:58 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/ContactsContentResolver.java
> +        if (cursor != null) {
исправил

2018-11-28 07:58 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/ContactsContentResolver.java
> +        ArrayList<String> listPhoneNumbers = new ArrayList<>();
исправил

2018-11-28 07:58 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/ContactsContentResolver.java
> +            while (phoneCursor.moveToNext()) {
исправил

2018-11-28 07:58 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +public class DetailFragment extends Fragment {
исправил

2018-11-28 07:58 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        tvName.setText("Name: " + contact.getName());
исправил

2018-11-28 07:59 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/MainActivity.java
> +    protected void onCreate(Bundle savedInstanceState) {
исправил

2018-11-28 07:59 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/service/DetailAsyncTask.java
> +        if (callback!=null){
удалил

2018-11-28 08:01 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        contactId = bundle.getString("_id", "Empty");
исправил

2018-11-28 08:17 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +    class ContactsViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
я делал `public`, студия порекомендовала понизить до package

2018-11-28 12:43 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +            itemClickListener.onClick(contacts.get(position).getId());
исправил

2018-11-28 12:51 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        tvName.setText(String.format("%s %s", getString(R.string.id), contact.getName()));
исправил

2018-11-28 12:51 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +    private final Context context;
исправил

2018-11-28 12:52 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +            name.setText(String.format("%s %s %s %s",
исправил

2018-11-28 12:52 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/service/AsyncResponseContactListFragment.java
> +public interface AsyncResponseContactListFragment {
удалил слово Fragment

2018-11-28 12:52 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/service/AsyncResponseDetailFragment.java
> +public interface AsyncResponseDetailFragment {
исправил

2018-11-28 12:52 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/service/ContactsContentResolver.java
> +class ContactsContentResolver {
Исправил

2018-11-28 14:17 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        args.putString("_id", id);
сделал

2018-11-28 14:18 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/service/ContactsAsyncTask.java
> +            callback.loadList(contacts);
добавил проверку `isResumed()` в реализацию во фрагмент

2018-11-30 11:30 UTC, RomanPozdeev approved these changes

2018-11-30 11:31 UTC, merged