My
AsiAsiAsiA/ContactsList pull request #2
Opened 2018-12-02 10:40 UTC by AsiAsiAsiA

Add Moxy MVP

2018-12-02 10:46 UTC, RomanPozdeev requested changes

2018-12-02 10:46 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/presenter/ContactsListPresenter.java
> +    }
В onDestroy презентера таску надо отменить

2018-12-02 10:46 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/view/ContactListView.java
> +    @StateStrategyType(AddToEndSingleStrategy.class)
Если есть действие которая показывает прогресс должно быть и действие которое его скрывает

2018-12-02 10:46 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/view/DetailView.java
> +    void loadContactFromContentProvider(Contact contact);
Название странное для вью

2018-12-02 11:15 UTC, goblinr requested changes

2018-12-02 11:15 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/presenter/ContactsListPresenter.java
> +        new ContactsAsyncTask().execute(context);
Утечка `context`. 

В данном случае,  `context` - это `Activity`, соответственно, жесткая ссылка на нее передается в `AsyncTask`. Ну и с точки зрения чистоты кода, это не верно передавать ссылку на `Context` в презентер, т.к. он становится зависимым от Android, а нам этого не нужно, т.к. наша цель сделать презентер "чистым" от платформенных вещей, что бы в будущем мы могли легко его протестировать.

2018-12-02 11:15 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/DetailFragment.java
> +        detailPresenter.loadContact(contactId, requireContext());
Утечка `context`.

2018-12-02 11:15 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        contactsListPresenter.getContactList(requireContext());
Утечка `context`.

2018-12-02 11:15 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/presenter/ContactsListPresenter.java
> +        new ContactsAsyncTask().execute(context);
Так же следует отменять `AsyncTask` в `onDestroy` презентера

2018-12-02 11:15 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/presenter/DetailPresenter.java
> +        new DetailAsyncTask().execute(context);
Утечка `context`.

2018-12-02 11:15 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/presenter/ContactsListPresenter.java
> +        getViewState().noPermissions();
`noPermissions` - не очень удачное название метода для `View`. Лучше что-то вроде `showPermissionsNotGranted`

2018-12-03 04:18 UTC, goblinr requested changes

2018-12-03 04:18 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/presenter/ContactsListFragmentPresenter.java
> +            getViewState().startLoading();
Желательно, проверить не отменен ли `AsyncTask` в данный момент

2018-12-03 04:18 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/presenter/ContactsListFragmentPresenter.java
> +            return ContactsManager.getContacts();
Желательно, проверить не отменен ли `AsyncTask` в данный момент

2018-12-03 04:18 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/presenter/DetailFragmentPresenter.java
> +            return ContactsManager.findContactById(id);
Желательно, проверить не отменен ли `AsyncTask` в данный момент

2018-12-05 08:05 UTC, goblinr approved these changes

2019-01-20 14:26 UTC, RomanPozdeev approved these changes

2019-01-20 15:13 UTC, merged