Diffutil
AsiAsiAsiA/ContactsList pull request #3
Opened 2018-12-21 05:53 UTC by AsiAsiAsiA

useItemDecoration, DiffUtil, SearchView

2018-12-22 08:30 UTC, goblinr requested changes

2018-12-22 08:30 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        ContactsAsyncTask contactsAsyncTask = new ContactsAsyncTask(query, this);
ссылку на `this` обычно принято передавать первым параметром

2018-12-22 08:30 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactListItemDecorator.java
> +    private static final int HALF_OFFSET = OFFSET / 2;
Захарткоженные размеры, да еще и в пикселях. Это приведет к тому, что на разных dpi экраннах - будут различные отступы

2018-12-22 08:30 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactListItemDecorator.java
> +        paint.setStrokeWidth(5);
Захардкоженный размер

2018-12-22 08:30 UTC, goblinr commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +        this.contacts = contacts;
1) `calculateDiff` следует вызывать на отдельном потоке программы.
2) вызывать `dispatchUpdatesTo` нужно после того как обновились данные в адаптере.

2018-12-24 08:24 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactsAdapter.java
> +        this.contacts = contacts;
Здесь с помощью RxJava сделал

2019-01-20 14:33 UTC, RomanPozdeev requested changes

2019-01-20 14:33 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/adapter/ContactListItemDecorator.java
> +        Resources r = App.getContext().getResources();
однобуквенные имена переменных, если не в for - то не очень хорошее решение.

2019-01-20 15:09 UTC, RomanPozdeev approved these changes

2019-02-05 13:25 UTC, merged