Dagger
AsiAsiAsiA/ContactsList pull request #5
Opened 2019-01-23 17:54 UTC by AsiAsiAsiA

2019-01-24 10:24 UTC, RomanPozdeev requested changes

2019-01-24 10:24 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        AndroidSupportInjection.inject(this);
для фрагментов это нужно делать в onAttach

2019-01-24 10:24 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
>      public void loadList(List<Contact> contacts) {
Если параметр может быть null, то лучше пометить его как @Nullable

2019-01-24 10:24 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/presenter/ContactsListFragmentPresenter.java
> +        if (disposable != null && !disposable.isDisposed()) {
Добавить этот же код в onDestroy

2019-01-24 10:24 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/presenter/ContactsListFragmentPresenter.java
> +                .doOnSubscribe(__ -> getViewState().startLoading())
в java не принято помечать __ - это не котлин

2019-01-24 10:24 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/presenter/ContactsListFragmentPresenter.java
> +                .subscribe(this::loadList);
Лучше всегда добавлять обработчик ошибок

2019-01-24 10:24 UTC, RomanPozdeev commented on app/src/main/java/com/example/semen/contactslist/service/ContactsManager.java
> +            return contact;
Потенциально contact может быть Null, попытка заэмитить null в RxJava2 вызовет NPE - лучше кинуть какое-нибудь NotFound* исключение

2019-01-24 14:50 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/ContactListFragment.java
> +        AndroidSupportInjection.inject(this);
исправил

2019-01-24 14:51 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/presenter/ContactsListFragmentPresenter.java
> +        if (disposable != null && !disposable.isDisposed()) {
Исправил

2019-01-24 14:51 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/presenter/ContactsListFragmentPresenter.java
> +                .doOnSubscribe(__ -> getViewState().startLoading())
Здесь изменил

2019-01-24 14:51 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/presenter/ContactsListFragmentPresenter.java
> +                .subscribe(this::loadList);
Добавил кастомный NotFoundContactException

2019-01-24 14:52 UTC, AsiAsiAsiA commented on app/src/main/java/com/example/semen/contactslist/service/ContactsManager.java
> +            return contact;
Добавил кастомный NotFoundContactException

2019-01-25 05:44 UTC, RomanPozdeev approved these changes

2019-02-04 08:54 UTC, merged